<?php


namespace Tests;


use App\Model\AccountModel;
use App\Model\ConfigModel;
use HuanL\Core\Application;
use PHPUnit\Framework\TestCase;

class RadiusTest extends TestCase {

    protected function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        require '../vendor/autoload.php';
        $app = new Application(
            realpath(__DIR__ . '/../')
        );
    }

    public function testMd5() {
        echo substr(b);
        echo md5("ha\x0");
    }

    public function testOnline() {
        $accountModel = new AccountModel();
        $configModel = new ConfigModel();
        self::assertLessThanOrEqual($configModel->getConfigVal('online_num'), $accountModel->onlineNumber(4));
    }
}